### ISSUE TITLE
History show wrong Amount of Token for each transaction

### ISSUE THREAD

**Issue by thuydx55** [DeltaBalances/DeltaBalances.github.io#12]
This guy `0xbfffc0478d4ebf6d44eced13743d08c0c967d228` buy `IBTC` 3 times. He has total 3311 IBTC.

In history tab, it shows that there're 3 transactions and each of them has value of 3312 IBTC

**Comment by DeltaBalances** [comment]
The history tab shows me 3 trades of volumes 0.031, 0.000003 and 3310.969.

Maybe you looked only at the input in the recent transactions.
