### ISSUE TITLE
Address history not showing dates for any trade

### ISSUE THREAD

**Issue by coinaisseur** [DeltaBalances/DeltaBalances.github.io#14]
Good afternoon,

I'm using Delta Balances to export my daily trade history. When finished, dates don't show either on the Trades page or in the CSV export, instead showing "??" for all dates. I could live with that, but in the CSV export, the Block column just disappears entirely, so I have no way of knowing when any trade took place. Please see the attached screenshot.

Thanks for your help!
![db_issue1](https://user-images.githubusercontent.com/33495445/33696991-5761158a-daca-11e7-85ed-75d8e62d908a.JPG)

**Comment by DeltaBalances** [comment]
Dates are retrieved from etherscan based on the block numbers, and lately etherscan sometimes becomes unresponsive (cryptokitties?). If you try again a little later it will probably work again.

Nevertheless, I just added the block number to the default csv export.

**Comment by coinaisseur** [comment]
@DeltaBalances Yeah, the issue started with CryptoKitties. Anyways, I can get away with the block number; after all, I just need a way to sort trades from newest to oldest.
Thank you a lot for your help.
