### ISSUE TITLE
deltabalances: reporting one fiscal year runs infinitely

### ISSUE THREAD

**Issue by lotstep** [DeltaBalances/DeltaBalances.github.io#17]
Could the logic be implemented faster ?:
1. read all ED-TX in the walletadress
2. read precisely the TX in the wallet
3. write the TX information on the screen

So it should be able to analyze one year of TX in minutes.

**Comment by DeltaBalances** [comment]
When someone matches your maker order, there is no trace of it left in your wallet's transactions (try finding one on etherscan). The only way to find those is to get all etherdelta trades and filter for your address.

Maybe try searching in ranges of about 30 days and combining the 10 exports.
