### ISSUE TITLE
Block range estimation is confusing

### ISSUE THREAD

**Issue by GerdC** [DeltaBalances/DeltaBalances.github.io#18]
Hi,

when I select 999 days on history.html, the first selected block is 322 days old. This is a problem. Not enough for taxes for a year.

It is also impossible, to manually select an earlier start block than the one that is estimated from the "999" days.

This problem is probably also the case on the deltabalances page, where the block range is invisible.

I would expect that the days roughly select a block that is near that date.
I would expect to be able to select a start block that is earlier than what the script thinks is 999 days.

Thanks,
Gerd

**Comment by DeltaBalances** [comment]
Right now it limits the blockrange to this transaction https://etherscan.io/tx/0xc10fc67499a037b6c2f14ae0c63b659b05bd7b553378202f96e777dd4843130f , where the current EtherDelta contract was created.

**Comment by GerdC** [comment]
This makes very much sense, thank you.

Then the only suggestion I have is to state on the website that this is the first block of the contract that is currently shown on the page.
