### ISSUE TITLE
Cointracking csv export: wrong fees

### ISSUE THREAD

**Issue by WideAwakeTN** [DeltaBalances/DeltaBalances.github.io#19]
For cointracking.info to correctly process the csv export fields of the column "Sell" or "Buy" (depending on transaction type) must include the value of the column "Fee" of the same row. For example selling 1 ETH with a fee of 0.1ETH the the field in the "Sell" column should state "1.1" and the respective field "Fee" in the same row should state "0.1". The respective "Cur." entries in the same row both contain "ETH".

Reason: contracking.info treats the field "Fee" as optional. It is NOT used for calculation of balances (strange, but true).

Note: Thx for the exporter!

**Comment by DeltaBalances** [comment]
Thanks, I never really used the site besides the import feature itself so I didn't notice this little 'feature'.

Added the fees to the amounts and it should be correct now.
