### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by davelab6** [DeltaBalances/DeltaBalances.github.io#22]
Please apply an open source license (perhaps GPLv3?) by creating a LICENSE.txt file.

**Comment by DeltaBalances** [comment]
Never really bothered to do this, but here you go.

Based on the following integrated projects, I assume that all their required node modules comply with GPLv3 as well.
[Bignumber.js](https://github.com/MikeMcl/bignumber.js/) -> MIT
[ethers.js](https://github.com/ethers-io/ethers.js) -> MIT
[web3.js](https://github.com/ethereum/web3.js/) -> GPLv3
[abi-decoder](https://github.com/ConsenSys/abi-decoder) -> GPLv3
