### ISSUE TITLE
What API are you using for event logs?

### ISSUE THREAD

**Issue by EeevilPopTart** [DeltaBalances/DeltaBalances.github.io#24]
I've noticed that etherscan's event logs API is sometimes delayed by hundreds of blocks (ouch).  And it has harsh rate limits which prevent you from getting an entire couple days worth of event logs quickly.  Yours doesn't seem to be delayed, is much closer to real time, and doesn't seem to be hit by rate limits such as etherscan's.  Hence my question, what API are you using to get event logs?  Are you running a node or using some API through Infura?

**Comment by DeltaBalances** [comment]
Yup its simply infura.
The method eth_getLogs with jsonrpc calls to mainnet.infura.io/

Also works with a local node if you simply swap the urls to localhost, but that actually seems to be slower.
Only people asking for like 100+ days of blocks sometimes get throttled or have some failed requests.

**Comment by EeevilPopTart** [comment]
Great, thanks!  Yeah this seems much more responsive.
