### ISSUE TITLE
Balance at a given block/date (history)

### ISSUE THREAD

**Issue by dxadxa** [DeltaBalances/DeltaBalances.github.io#26]
Today, the balance is done only for the latest block. 

It would be very nice to have the possibility to decide to display the balance for another blocknumber/date (for example I need it for the date 31st Dec 2017) ! (It is not needed to have the estimated ETH at that date, but just the balance of token). 

There is a similar feature in etherscan for ETH.

Thank you in advance!

**Comment by DeltaBalances** [comment]
Since this tool relies on etherscan and infura to get the required information, either one of those would need to provide an easy way to check the past values of a smart contract.

I haven't been able to find that yet.

I like the idea, but I dont see how to implement it as of now.
