### ISSUE TITLE
Error: Failed to load all Wallet balances after 3 tries, try again later

### ISSUE THREAD

**Issue by canpoyrazoglu** [DeltaBalances/DeltaBalances.github.io#27]
I am unable to query my EtherDelta balance using Safari.
I've tried quite a few times. It does load my total ETH balance and estimated token value with no issues, but after a few seconds I'm getting the error: Failed to load all Wallet balances after 3 tries, try again later.

What might be wrong?
(It works fine on Chrome)

**Comment by DeltaBalances** [comment]
Sorry for the slow response, Safari should now behave identical to chrome.
