### ISSUE TITLE
Add improved support for ForkDelta tokens

### ISSUE THREAD

**Issue by pricejn2** [DeltaBalances/DeltaBalances.github.io#28]
URL: https://forkdelta.github.io
Repo: https://github.com/forkdelta/tokenbase

Right now, tokens that are listed on FD but not ED do not show up on the primary Balances tab. However, they do show up under trade history.

**Comment by DeltaBalances** [comment]
Did you check the 'show unlisted tokens' checkbox?
It is off by default as it makes loading slower. Might have to change things up since etherdelta isn't really updating tokens anymore.

**Comment by pricejn2** [comment]
Yeah, you're totally right. The show unlisted option yields the same result as trade history. Sorry for missing that obvious option.

There is probably still some room for improvement to accommodate what FD is doing.
