### ISSUE TITLE
Transferred ETH funds and ordered POLY tokens not showing after 5+days

### ISSUE THREAD

**Issue by isauditor** [DeltaBalances/DeltaBalances.github.io#31]
Hi! Ref Trx: 0x34937466b5d914f6515a41aef12a8a0e960dd77635d5e934107bf5451d679b7c 
I transferred on Feb 9, 2018, 0.8 ETH to my EtherDelta account and placed an order to buy POLY tokens with that amount. After 5+ days I dont see either the transferred Ether or the ordered POLY tokens. Please help. Thank you.

**Comment by DeltaBalances** [comment]
This isn't really the place of etherdelta support. But if you enter your address on the history page, you have multiple buys for POLY, and you withdrew 800 of them.
