### ISSUE TITLE
Missing CORS-headers for forkdelta

### ISSUE THREAD

**Issue by iSnow** [DeltaBalances/DeltaBalances.github.io#34]
Getting "Failed to load https://api.forkdelta.com/returnTicker: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://deltabalances.github.io' is therefore not allowed access." while trying to show my balances. 

You'll probably need to the forkdelta guys or proxy the call on your back-end.

**Comment by freeatnet** [comment]
Keen eye, @iSnow! It's our fault, really, we'll get it fixed.

cf. https://github.com/forkdelta/backend-replacement/issues/43

**Comment by iSnow** [comment]
Thanks, good job!
