### ISSUE TITLE
Smart Contract Issue

### ISSUE THREAD

**Issue by MsCryptoTee** [DeltaBalances/DeltaBalances.github.io#35]
Hello, I have a smart contract that was created and added to my account on December 19, 2017. I have been trying to retrieve the ETH from the contract and have not been successful. I followed all of the instructions that are posted on Decentrex regarding the contract and nothing is working. I contacted the wonderful staff at Etherscan.io, they advised me to contact the exchange for help. I have Metamask, tried to access the contract with Metamask and it did not work. I am at a loss at this point. Can anyone explain  this contract to me and provide instructions on how to withdraw from the contract. Thank you for your time and assistance! Wishing you a great day!

Thank you,
Tawanna Sloan
![screenshot 66](https://user-images.githubusercontent.com/36830546/36935378-62a6b552-1eb4-11e8-8791-d033da2f4df0.png)
![screenshot 67](https://user-images.githubusercontent.com/36830546/36935385-74b325c8-1eb4-11e8-9edc-5b5f62d75616.png)

**Comment by DeltaBalances** [comment]
Try using this guide https://www.reddit.com/r/EtherDelta/comments/6hrxjw/etherdelta_guides_for_first_time_users/dn6heno/
In the requirements, replace the etherdelta contract and ABI with the decentrex ones found here https://etherscan.io/address/0xbF29685856FAE1e228878DFB35B280C0adCC3B05

**Comment by MsCryptoTee** [comment]
Thank you so much for your help! I followed the instructions, it seemed to work until the last step, once I click the write button, I receive an insufficient funds message. I am still pretty much confused on the requirements or what I am doing wrong. 
![screenshot 68](https://user-images.githubusercontent.com/36830546/36961996-f5baa7de-200a-11e8-8b87-1b41baeaee62.png)

**Comment by DeltaBalances** [comment]
You need some Ether in your wallet to be able to make those transactions. Try to keep like 0,1 ET or more available.
Another option might be that the gas limit was set too low. Keep it around 150-250k to be safe.

**Comment by MsCryptoTee** [comment]
Okay, thank you!
