### ISSUE TITLE
Add DDEX on DeltaBalances 

### ISSUE THREAD

**Issue by bw992** [DeltaBalances/DeltaBalances.github.io#36]
Dear DeltaBalances, 

This is Bowen from DDEX, the most user-friendly decentralized exchange on Ethereum. Many of our users(including myself) are long-time users to DeltaBalance. Therefore, I want to reach out to you to see if you can integrate DDEX on your website. 

A quick intro about DDEX. DDEX is the demonstrative flagship hybrid decentralized exchange on top of Ethereum. Hybrid technology makes DDEX is capable of running an off-chain matching engine, match and settle trades 50x the speed of the previous generation decentralized exchanges. DDEX got funded from Sequoia China venture arm and YC partner Garry Tan, Reddit Co-Founder Alexis Ohanian. Below is the coverage on Wall Street Journal and The information.

https://www.wsj.com/articles/alexis-ohanians-vc-firm-invests-2-1-million-in-crypto-trading-platform-1520365270

We would love if DeltaBalances can integrate DDEX into its web. I have attached the API document below so your engineering team can take a look at it.

https://api.ddex.io/v2/markets/tickers

best, 

Bowen

**Comment by DeltaBalances** [comment]
0x is nwo supported in the recent transactions and transaction info pages.
History will be soon
