### ISSUE TITLE
How do you GET totall wallet ballance with Etherdelta API ?

### ISSUE THREAD

**Issue by hristosv1** [DeltaBalances/DeltaBalances.github.io#4]
EtherDelta API  allows you to see deposits and withdraws but I could not figure out how to GET total current ETH balance. Could you please help ?

**Comment by DeltaBalances** [comment]
Balances are not in the EtherDelta API. They are requested directly from the balanceOf functions in smart contracts on the blockchain.

**Comment by hristosv1** [comment]
What is the smart contract address ?

**Comment by DeltaBalances** [comment]
EtherDelta smart contract https://etherscan.io/address/0x8d12a197cb00d4747a1fe03395095ce2a5cc6819#code
