### ISSUE TITLE
Add Ethen.market

### ISSUE THREAD

**Issue by r3nat** [DeltaBalances/DeltaBalances.github.io#40]
Hello, @DeltaBalances

Is it possible to add new decentralized exchange [ethen.market](https://ethen.market/)?

**Comment by r3nat** [comment]
Do you accept pull requests?

**Comment by DeltaBalances** [comment]
I'll look into this one as well, but as theres <100 transactions on the contract for now, I didn't feel rushed yet to get it added immediately.

I'm in the process of gradually adding support for more (types of) exchanges. 0x sort of works now, and the next ones on the list are OasisDex and Bancor.


I'll accept pull requests if they work alright and add something useful. However the code base is still kind of a mess, so I'm not expecting much in that area for now.

**Comment by DeltaBalances** [comment]
Closing this issue in favour of #42 to keep a more general TODO list.
