### ISSUE TITLE
Globitex token decimals are wrong

### ISSUE THREAD

**Issue by fransla** [DeltaBalances/DeltaBalances.github.io#41]
DeltaBalances lists GBX (Globitex) as 18 decimals, but the correct decimals should be 8 according to the contract:
https://etherscan.io/address/0x12fcd6463e66974cf7bbc24ffc4d40d6be458283#readContract

**Comment by DeltaBalances** [comment]
Fixed, and I checked all others for issues as well.
Thanks for noticing!
