### ISSUE TITLE
Date range selection broken

### ISSUE THREAD

**Issue by awishformore** [DeltaBalances/DeltaBalances.github.io#49]
Your tool looked exactly like what I needed to work on my tax returns. Unfortunately, it seems the range selector is defunct. No matter what I do (selection by days, month or block numbers), when I click "Retrieve history", it wil always reset to blocks "Selected block range: 5710964 - 5883490" and retrieve the trades for this period. This makes it impossible to export trades outside of June 2018 at this point.

I tried with Chromium and Firefox, with disabled adblockers and extensions, and nothing seems to make a difference.

**Comment by DeltaBalances** [comment]
Whoops.
I changed the trade history page this weekend and this must have slipped between the cracks.

Should be fixed now. Might require some refreshing to clear your cache.

**Comment by awishformore** [comment]
Thank you for the quick reaction :+1:
