### ISSUE TITLE
Be able to access data via JSON

### ISSUE THREAD

**Issue by penta314** [DeltaBalances/DeltaBalances.github.io#5]
The functionality of the tool is 100% visually perfect.  However it would be great to have a way to call a URL to get the same data via JSON, that would allow importing specific data to google spreadsheets and so on.

**Comment by DeltaBalances** [comment]
Good idea. 
But I won't add this any time soon as that is server side functionality. 
Right now to keep it simple and cheap everything runs client side.

I'll think about it, but I can't promise anything.
