### ISSUE TITLE
Trade history retrieval stuck

### ISSUE THREAD

**Issue by awishformore** [DeltaBalances/DeltaBalances.github.io#50]
Hello, it's me again. When I click "Retrieve History", the events are collected all the way to what seems to be the last chunk of blocks (in my case "Loaded 2903920/2908921 blocks" for the whole timespan). The animation with the two arrows keeps running, so I am not able to download the CSV export.

**Comment by awishformore** [comment]
DDEXes used: EtherDelta, ZeroX (RadarRelay) and OasisDex.

**Comment by DeltaBalances** [comment]
Do smaller date ranges work alright? I never have any problems (besides slowness) when retrieve some days or a month.

Blocks are retrieved from external sources (mainly Infura) in chuncks of 5000.
Your nearly 3 million blocks result in 500+ requests sent their way.
I wouldn't be surprised if they end up throttling or ignoring you, and the tool is stuck missing a request.

I'll look more into reliability and better recovery from failures. But your best bet is to get you data in smaller chunks and copy/paste the exports together.
(thats why I try to coerce users into day/month selection)

**Comment by awishformore** [comment]
I will try, but it's still weird that it would always get stuck at just the last chunk of blocks (I tried several times).

**Comment by Jecherio** [comment]
![unbenannt1](https://user-images.githubusercontent.com/42511961/44308118-83c30300-a3af-11e8-9d2d-c41b4cdace57.JPG)

I am having the same issue. Even if i use a fixed intervall like  nov 2017.

Deltbalances also seems relatively slow for me at the moment. 

Maybe some backend issues?

**Comment by awishformore** [comment]
Sometimes, you have to divide the months into two, if it gets stuck.

**Comment by josoahgithinji** [comment]
Hi,
I just ask whether you can help?
My MEW Wallet was hacker sometimes ago.
The Hacker placed a Bot so that When T try to transfer any Token from over
350 tokens in that wallet its Stolen?
Am in a difficult situations I need Help or where I can refer my Problem to?
Josiah Githinji

**Comment by DeltaBalances** [comment]
I've updated things so that failed blocks shouldn't get stuck anymore like this.
As long as Infura is online and responding it should resolve.

I can't really improve the speed with the current approach as I'm lucky enough that Infura allows this much requests to their ethereum nodes.
