### ISSUE TITLE
Checking approvals

### ISSUE THREAD

**Issue by cloudonshore** [DeltaBalances/DeltaBalances.github.io#51]
Hello,
  I was wondering if you were aware of any contracts that would allow me to check ERC20 approvals (allowances) for multiple addresses/tokens in a single call. Thanks so much for your great work.

**Comment by DeltaBalances** [comment]
In case you or anyone else still needs this.
I published a contract that also allows this [Here](https://etherscan.io/address/0x40a38911e470fC088bEEb1a9480c2d69C847BCeC).

Will add this to the website for exchanges like 0x soon. For now you could try interfacing with the contract either manually on etherscan 'Read Contract' or in code.
