### ISSUE TITLE
Etherdelta transaction history - stuck scanning blocks

### ISSUE THREAD

**Issue by aio3** [DeltaBalances/DeltaBalances.github.io#53]
Thanks for building this much-needed tool. I've tried two different month date ranges and eventually it always gets stuck and will not continue to progress in scanning the blocks even after substantial waiting times (30-60 minutes). Usually this happens when it's about 2/3 through the total number of blocks for that month. I've never been able to complete the scan for a month. What can I do?

**Comment by SympathyMotel** [comment]
I was having the same problem as aio3. I copied the url and pasted it into an incognito browser and it worked much MUCH faster, even when selecting multiple exchanges. Might be something to do with the browsers cache?
