### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by SympathyMotel** [DeltaBalances/DeltaBalances.github.io#56]
When I load https://deltabalances.github.io and put in my address to scan for tokens, I am unable to click on the links to open the forkdelta page. This only applies to me on Chrome, firefox works fine.

https://deltabalances.github.io/trades.html allows me to click on the token and select an option, but balances.github does not allow

**Comment by DeltaBalances** [comment]
Apologies for the slow response.
Can you try if they work now?
