### ISSUE TITLE
REQUEST: enable multiple addresses

### ISSUE THREAD

**Issue by rory4ever** [DeltaBalances/DeltaBalances.github.io#58]
I really love this wonderful tool. However, at the moment I have around 10 ETH wallets and right now I have to open a new tab in my browser for each address. And I need to refresh each page too and click on "retrieve history" every time for every single address. Is there a way to alter in the address input field (or create additional input fields) so that one can enter multiple eth addresses? Is this possible? It would save me a lot of time. Thanks in advance.

**Comment by rory4ever** [comment]
Do you have any news regarding this request? Thanks in advance :)

**Comment by DeltaBalances** [comment]
This was actually already partially done, but I got sidetracked and never fully finished it.

I added the ability to add up to 5 other addresses to your search. 

As I kind of rushed it right now:
+ It only works on the history related pages.
+ It is sort of a hidden feature, no realy UI changes yet, but it does function as it should.

How to use it:
+ Separate addresses with a comma in the search bar `address1, address2`.
+ Or separate them with a dash in the url `trades.html#address1-address2`.

**Comment by rory4ever** [comment]
No worries :) 
Thank you. I've tried it and it works as expected. However, the results are shown in the same way as a single-address search would do so it is hard to distinguish the trades from the multiple addresses.   
I did the following: 
- in the address bar I copied 3 addresses separated with a dash as you mentioned (note: the , in the search bar does not seem to work?) and I see the 3 different addresses showing under the "main" address input field. 
- I am sure to use 3 addresses which all have trades in the selected date range.
- Clicked on "retrieve history" and I see all trades from all 3 accounts, which is good. 
- However, there is only 1 list and there is no way to tell which trade is from which address. Is there a way to add a column or any other way to show it? 
Thanks

**Comment by Groove8888** [comment]
Hey @DeltaBalances,

I would actually be interested in this function too! :)

Basically, I'd like the option to check multiple addresses and query the token balances, both available in the actual wallet and load deposited on certain exchanges - pretty much exact same flow as the current home page, just the ability to import multiple addresses at the same time.

Would this be something you would consider? Also, I don't mind making a donation to have this feature enabled :)

Thank you!

**Comment by DeltaBalances** [comment]
@Groove8888
Loading balances for multiple addresses will slow things down, but shouldn't be hard to add.
How would you expect to see the output? The same table, just with the combined sum?

I'm thinking of rewriting the old core code of the website, so that might be an opportunity to properly add multi-address support. (and also finally closing this issue)

**Comment by Groove8888** [comment]
Hey @DeltaBalances 
In a perfect world I would:
a) have the option to paste multiple addresses separated by comma or import a .txt file that has multiple addresses
b) Have a layout similar to this - https://prnt.sc/s80oyx - where I can see the grand total of all addresses combined (see top section) and then have a report for each individual address, exactly as it is at the moment 

What do you think?
Thank you!
