### ISSUE TITLE
Request for export: TokenTax

### ISSUE THREAD

**Issue by milesalex** [DeltaBalances/DeltaBalances.github.io#59]
Hey there!

Lovely product!! I'm wondering if I could submit a PR to export to TokenTax? https://tokentax.us

**Comment by DeltaBalances** [comment]
I just cleaned up the exporting code a little to make this somewhat easier. Although it still isn't pretty.

Look in `history.js` for `generateTradesData` which does this for BitcoinTax and Cointracking.
It isn't really documented but it shouldn't be too hard to piece together by looking at the others.
The UI dropdowns are hardcoded in html as of now, so you would have to manually add an option there.

Alternatively, if you can provide a nice example of what format tokentax accepts, I could add it as well.

**Comment by milesalex** [comment]
The TokenTax format is similar to CTinfo but has a different header: https://cl.ly/6eb33d916010

**Comment by DeltaBalances** [comment]
Do the dates have to be in `mm/dd/yy hh:mm` or can I use something like ISO 8601 ?.

**Comment by milesalex** [comment]
ISO is good!

**Comment by DeltaBalances** [comment]
Added it to the trade history page, let me know if this works.

**Comment by milesalex** [comment]
You're a star!!! 😍
