### ISSUE TITLE
Cointracking Export has mixed up columns

### ISSUE THREAD

**Issue by nichtdu** [DeltaBalances/DeltaBalances.github.io#63]
Hey,

Currently Export is set to: 
"Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment",**"Trade ID","Date"**

Cointracking Import Format is
"Type","Buy","Cur.","Sell","Cur.","Fee","Cur.","Exchange","Group","Comment",**"Date","Trade ID"**

**Comment by DeltaBalances** [comment]
Thanks, it's fixed.
