### ISSUE TITLE
Trade direction gets swapped on some trades from OasisDex

### ISSUE THREAD

**Issue by kjekac** [DeltaBalances/DeltaBalances.github.io#68]
Steps to reproduce:

1. Generate statistics for the block `5976037` using https://deltabalances.github.io/history7.html#0xa32506582cafdf8b9b301f239674b0735358a48a
2. Compare the single output entry to [its transaction](https://etherscan.io/tx/0xd884724d1f42d5c22814d8991bd90e62ba66202de9205507e6f3518254b45d11).

As far as I can see, this is wrong. `0xa32506` gains WETH in the transaction, but in the entry produced by DeltaBalances, they buy DAI using WETH.

It seems like this might be related to the logic of detecting maker/taker. If you expand the block range to `5976037`-`5992316` in order to include one more trade and compare that entry to its transaction, you will see that it is correctly reported as a sell, but this time `0xa0addc` is the taker , rather than the maker as in the example which is reported as a buy. (Maker/taker roles seem to be correctly reported.) I've had this pattern appear with other trades on other addresses too.

**Comment by DeltaBalances** [comment]
The event was parsed correctly from the taker perspective (taker buy).
It switched to maker on the history page as you view it from a certain address, apparently in this event I forgot to switch buy/sell as well.

**Comment by kjekac** [comment]
Awesome, things seem to work now, thanks for the speedy fix! :)
