### ISSUE TITLE
Known tokens not shows and ETH balance.

### ISSUE THREAD

**Issue by Dariloff** [DeltaBalances/DeltaBalances.github.io#7]
Not all known etherdelta tokens shows. For example, SUB1X. You can test by my address 0x34cb52c6d97521e9b51b05c2860c8a448ffcef5c.
Also, "Total ETH balance" shows me 1.157920892373162e+59.

**Comment by DeltaBalances** [comment]
Your SUB1X is such a low number that it got rounded down to zero, which was automatically hidden. Check 'show more decimals' for it to show up. (possibly unwanted behavior)

I'll look into the exponential notation thing.
