### ISSUE TITLE
Transaction info from trade history page does not work anymore

### ISSUE THREAD

**Issue by rory4ever** [DeltaBalances/DeltaBalances.github.io#76]
I'd like to report a (little) bug which is occurring since 2-3 weeks now. 

Reproduction path: 

- load an (active) ERC20 wallet address in the trade history page, set the date range to something that it will show a couple of trades. 
- click on the three dots (...) under the "info" column. 
**expected result**: you will see the transaction info page with complete information like the summary, input data, output data, etcetera. 
**actual result**: you will see the transaction info page but it lacks almost all information, you will only see the hash address, nothing more. See attached screenshot
![12](https://user-images.githubusercontent.com/39132289/80414571-89d1ec80-88d1-11ea-8e7f-7ce8473819ea.png)

However, when you go directly to the transaction info page (from the menu at the left of the screen) and you paste the transaction hash, it will load correctly. Tried it with 2 different browsers on ubuntu 18.04.4 LTS

**Comment by DeltaBalances** [comment]
It should be fixed now.

Immediately after loading a lot of history, the APIs for ethereum will respond slower.
There was a little bug in handling a connection timeout on the tx details page.

Loading the page when everything responds normally would not trigger it.

**Comment by rory4ever** [comment]
Tested it and works fine now, thanks.
