### ISSUE TITLE
see "maker" transactions also

### ISSUE THREAD

**Issue by dxadxa** [DeltaBalances/DeltaBalances.github.io#8]
It would be great if we could see in "Recent Transactions", the trades that are done when the account is "maker" (curently we see only "taker" ones)!

(BTW, you are doing a great job!)

**Comment by DeltaBalances** [comment]
Since those require a much slower process to find them, it would really slow down the experience of the main overview. 

You can find them on the history tab.

**Comment by dxadxa** [comment]
Great ! You are right ! Thank you !
